### ISSUE TITLE
ImportError: 'group_by_date' from 'dolphin.utils'

### ISSUE THREAD

**Issue by taliboliver** [isce-framework/sweets#19]
After installing the latest sweets and installing environment packages using conda I get the following error: `ImportError: cannot import name 'group_by_date' from 'dolphin.utils'`. It seems that the error is due to an older version of dolphin that was installed. For reference the dolphin installed was version 0.1.1 while the current version is 0.2.0. In contrast, the version of COMPASS installed was the current one 0.4.1.

**Comment by scottstanie** [comment]
Close by the version pinning done in #20 

```
$ mamba env create -n test-sweets-pins --file conda-env.yml
.....
  + dolphin                           0.3.0  pyhd8ed1ab_0             conda-forge/noarch         97kB
....
```
